### ISSUE TITLE
11.7.17 has a 12.4 splash screen?

### ISSUE THREAD

**Issue by stefandrissen** [progress/ADE#3]
The last commit to adeicon/u-logo.bmp for [release 11.7.17.0](https://github.com/progress/ADE/releases/tag/v11.7.17.0) updates the splash screen from a generic Powered by Progress:

![](https://github.com/progress/ADE/blob/v11.7.16.0/adeicon/u-logo.bmp?raw=true)

To Progress OpenEdge 12.4:

![](https://github.com/progress/ADE/blob/v11.7.17.0/adeicon/u-logo.bmp?raw=true)

**Comment by swaohan** [comment]
Updated the correct splash screen.
